export enum AuthExceptionEnum {
  VALIDATION_EXCEPTION = "VALIDATION_EXCEPTION",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  CODE_PASSWORD_NOTFOUND = "CODE_PASSWORD_NOTFOUND",
  CODE_PASSWORD_EXPIRED = "CODE_PASSWORD_EXPIRED",
  UNAVAILABLE_ROUTE = "UNAVAILABLE_ROUTE",
  UNAUTHORIZED = "UNAUTHORIZED",
}

export enum HttpExceptionEnum {
  UNPROCESSED_ENTITY = "UNPROCESSED_ENTITY",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  VALIDATION_EXCEPTION = "VALIDATION_EXCEPTION",
  NOT_FOUND = "NOT_FOUND",
}

export enum HttpExceptionStatusCodeEnum {
  UNAUTHORIZED = 401,
  TOO_MANY_REQUESTS = 429,
  BAD_REQUEST = 403,
}

export enum FileUploadExceptionEnum {
  FILE_IS_REQUIRED = "FILE_IS_REQUIRED",
}
